<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Invoice <?= $this->e($invoice['invoice_number']) ?> — <?= $this->e($invoice['freelancer_company'] ?: $invoice['freelancer_name']) ?></title>
    <link rel="stylesheet" href="<?= asset('/assets/css/print.css') ?>">
</head>
<body onload="window.print()">
    <div class="print-page">
        <div class="print-header">
            <div class="freelancer-block">
                <h1 class="freelancer-title"><?= $this->e($invoice['freelancer_company'] ?: $invoice['freelancer_name']) ?></h1>
                <p class="freelancer-contact"><?= $this->e($invoice['freelancer_email']) ?></p>
            </div>
            <div class="meta-block">
                <h2 class="invoice-word">INVOICE</h2>
                <p><strong>Invoice #:</strong> <?= $this->e($invoice['invoice_number']) ?></p>
                <p><strong>Date:</strong> <?= date('F j, Y', strtotime($invoice['issue_date'])) ?></p>
                <p><strong>Due:</strong> <?= date('F j, Y', strtotime($invoice['due_date'])) ?></p>
                <p><strong>Status:</strong> <?= strtoupper($invoice['status']) ?></p>
            </div>
        </div>

        <hr class="divider">

        <div class="client-block">
            <h3>BILLED TO:</h3>
            <p class="client-name"><?= $this->e($invoice['client_name']) ?></p>
            <?php if (!empty($invoice['client_company'])): ?>
                <p><?= $this->e($invoice['client_company']) ?></p>
            <?php endif; ?>
            <p><?= $this->e($invoice['client_email']) ?></p>
            <?php if (!empty($invoice['client_phone'])): ?>
                <p><?= $this->e($invoice['client_phone']) ?></p>
            <?php endif; ?>
        </div>

        <table class="print-table">
            <thead>
                <tr>
                    <th style="width: 60%;">Description</th>
                    <th class="text-center" style="width: 15%;">Qty</th>
                    <th class="text-right" style="width: 12%;">Rate</th>
                    <th class="text-right" style="width: 13%;">Total</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($invoice['items'] as $item): ?>
                    <tr>
                        <td><?= $this->e($item['description']) ?></td>
                        <td class="text-center"><?= number_format((float)$item['quantity'], 2) ?></td>
                        <td class="text-right"><?= format_currency((float)$item['unit_price'], $invoice['currency']) ?></td>
                        <td class="text-right"><?= format_currency((float)$item['total'], $invoice['currency']) ?></td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>

        <div class="totals-section">
            <div class="notes-col">
                <?php if (!empty($invoice['notes'])): ?>
                    <h4>Payment Instructions:</h4>
                    <p><?= nl2br($this->e($invoice['notes'])) ?></p>
                <?php endif; ?>
            </div>
            <div class="numbers-col">
                <div class="line"><span>Subtotal:</span> <strong><?= format_currency((float)$invoice['subtotal'], $invoice['currency']) ?></strong></div>
                <?php if ((float)$invoice['tax_amount'] > 0): ?>
                    <div class="line"><span>Tax (<?= $invoice['tax_rate'] ?>%):</span> <strong><?= format_currency((float)$invoice['tax_amount'], $invoice['currency']) ?></strong></div>
                <?php endif; ?>
                <div class="line grand-total"><span>Total Amount:</span> <strong><?= format_currency((float)$invoice['total_amount'], $invoice['currency']) ?></strong></div>
            </div>
        </div>

        <?php if ($invoice['status'] === 'paid'): ?>
            <div class="paid-stamp">PAID IN FULL</div>
        <?php endif; ?>

        <div class="print-footer">
            Thank you for your business! · Generated by WorkShift Freelance CRM
        </div>
    </div>
</body>
</html>
